Failure # 1 (occurred at 2021-03-06_17-28-26)
Traceback (most recent call last):
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(FatalFlowError): [36mray::PPO.train_buffered()[39m (pid=22457, ip=192.168.0.18)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 526, in train
    raise e
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 515, in train
    result = Trainable.train(self)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayTaskError(FatalFlowError): [36mray::RolloutWorker.par_iter_next()[39m (pid=22455, ip=192.168.0.18)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py", line 1152, in par_iter_next
    return next(self.local_it)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 327, in gen_rollouts
    yield self.sample()
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 662, in sample
    batches = [self.input_reader.next()]
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 95, in next
    batches = [self.get_data()]
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 224, in get_data
    item = next(self.rollout_provider)
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 589, in _env_runner
    base_env.poll()
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 326, in poll
    self.new_obs = self.vector_env.vector_reset()
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 133, in vector_reset
    return [e.reset() for e in self.envs]
  File "/Users/Matteo/opt/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 133, in <listcomp>
    return [e.reset() for e in self.envs]
  File "/Users/Matteo/Documents/GitHub/flow/flow/envs/ring/wave_attenuation.py", line 210, in reset
    return super().reset()
  File "/Users/Matteo/Documents/GitHub/flow/flow/envs/base.py", line 543, in reset
    raise FatalFlowError(msg=msg)
flow.utils.exceptions.FatalFlowError: 
Not enough vehicles have spawned! Bad start?
Missing vehicles / initial state:
- rl_0: ('rl', 'left', 0, 60.177272727272765, 0)

